//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaMusicStoreWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class albumfd
    {
        public int albumID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> Duration { get; set; }
        public Nullable<int> artistID { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
